[workspace]
resolver = "2"
members = ["wayshot", "libwayshot","libwayshot/examples/waymirror-egl"]

[workspace.package]
authors = ["Shinyzenith <https://aakash.is-a.dev>"]
homepage = "https://waycrate.github.io"
description = "Screenshot crate for wlroots based compositors implementing the zwlr_screencopy_v1 protocol."
keywords = ["screenshot", "wayland", "wlroots", "wayshot"]
license = "BSD-2-Clause"
repository = "https://github.com/nashaofu/wayshot"
version = "1.3.2-dev"
edition = "2024"

[workspace.dependencies]
libwayshot-xcap = { version = "0.3.2", path = "./libwayshot" }
tracing = "0.1.41"
